//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace handshake.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("handshake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;style&gt;
        ///    h2 {
        ///      text-align: center;
        ///      font-family: calibri;
        ///    }
        ///
        ///    p {
        ///      text-align: center;
        ///      font-family: calibri;
        ///    }
        ///
        ///    .center {
        ///      display: block;
        ///      margin-left: auto;
        ///      margin-right: auto;
        ///    }
        ///  &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  &lt;div&gt;
        ///    &lt;h2&gt;You are invited&lt;/h2&gt;
        ///    &lt;p&gt;
        ///      1. Scan the code below with your phone to open the play store and install the app.&lt;br /&gt;
        ///      2. Scan the code again to signup.&lt;br /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvitePage {
            get {
                return ResourceManager.GetString("InvitePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;style&gt;
        ///    h1 {
        ///      font-family: calibri;
        ///    }
        ///	
        ///    h2 {
        ///      font-family: calibri;
        ///    }
        ///	
        ///    h3 {
        ///      font-family: calibri;
        ///    }
        ///
        ///    p {
        ///      font-family: calibri;
        ///    }
        ///	
        ///	li {
        ///      font-family: calibri;
        ///    }
        ///	
        ///	strong {
        ///	  font-family: calibri;
        ///    }
        ///  &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;Privacy Policy&lt;/h1&gt;
        ///&lt;p&gt;Last updated: October 22, 2020&lt;/p&gt;
        ///&lt;p&gt;This Privacy Policy describes Our policies and procedures on the collection, use and dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
    }
}
